### ISSUE TITLE
Doesn't stay connected to Bingosync server

### ISSUE THREAD

**Issue by Retrisma** [rhelmot/CelesteBingoClient#9]
Keeps disconnecting from the Bingo room, only staying connected for less than three minutes at a time. Can still mark off objectives when disconnected, but doesn't seem to receive anything back (still sees objective as unmarked.)

**Comment by Retrisma** [comment]
In a similar vein, it doesn't know when it has been disconnected and doesn't auto-reconnect, the user must disconnect and reconnect manually from the mod options menu. Maybe a timeout could work?

**Comment by rhelmot** [comment]
The problem is that the websocket bingosync uses to send us updates is dying. this is a frustrating problem because there's no information we send over that websocket, so there's no way to distinguish the situation where there's just no information to send from the situation where the socket quietly dies.

there's the additional complication that everyone experiencing this bug seems to be on windows, and I've only been doing testing on linux. I'll try to steal my partner's laptop to do some testing tonight.

**Comment by rhelmot** [comment]
Just kidding, this actually seems to be just https://stackoverflow.com/questions/40502921/net-websockets-forcibly-closed-despite-keep-alive-and-activity-on-the-connectio. I confirmed that bingosync sends the Content-Length: 0 header
